Fix pulsar connector issue with `NoSuchMethodError` (#7247)
Pulsar is using more recent version of `apache-codec` while Pinot
code base pins it to very old version. This causes the conflict
where pulsar side code invokes the API that's not available in the
jar file that we include as part of Pinot jar. This fixes the issue.